/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.99
 * Generated at: 2025-01-06 06:45:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.event;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class eventUpd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1717224129673L));
    _jspx_dependants.put("jar:file:/C:/semiproject/thenolja/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("     \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>더놀자 > 이벤트 > 수정</title>\r\n");
      out.write("<style>\r\n");
      out.write("#txtArea_content{\r\n");
      out.write("	width:650px;\r\n");
      out.write("	height:350px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".th_left{\r\n");
      out.write("    width:475px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#spn_textcount{\r\n");
      out.write("	float:right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#td_status_left{\r\n");
      out.write("	float:left;\r\n");
      out.write("	border: 1px solid #17a2b8;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#save{\r\n");
      out.write("    background: #17a2b8;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    border: 1px solid #17a2b8;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#cancel{\r\n");
      out.write("	background:#b6b6b6;\r\n");
      out.write("	border:1px solid #b6b6b6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".radio-btn{\r\n");
      out.write("    position: relative;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    margin: 5px 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 게시여부 라디오버튼 영역 스타일적용 START */\r\n");
      out.write(".radio-btn-wrap{\r\n");
      out.write("	margin:-5px -4px;\r\n");
      out.write("	float:left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".radio-btn{\r\n");
      out.write("	margin: 5px 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".radio-btn-wrap .radio-btn input[type=\"radio\"] {\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    width: 0;\r\n");
      out.write("    height: 0;\r\n");
      out.write("    opacity: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".radio-btn-wrap .radio-btn input[type=\"radio\"]:checked + label{\r\n");
      out.write("    \r\n");
      out.write("    background: #17a2b8;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    border: 1px solid #17a2b8;\r\n");
      out.write("    \r\n");
      out.write("    /*background: cadetblue;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    border: 1px solid cadetblue;*/\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".radio-btn-wrap .radio-btn label {\r\n");
      out.write("    display: block;\r\n");
      out.write("    height: 40px;\r\n");
      out.write("    padding: 0 15px;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    color: #636366;\r\n");
      out.write("    line-height: 38px;\r\n");
      out.write("    border: 1px solid #17a2b8;\r\n");
      out.write("    /*border: 1px solid cadetblue;*/\r\n");
      out.write("    border-radius: 24px;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write(".filebox{\r\n");
      out.write("	margin-top:8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".filebox label {\r\n");
      out.write("	float:left;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    width: 140px;\r\n");
      out.write("    height: 48px;\r\n");
      out.write("    padding: 0 12px;\r\n");
      out.write("    color: #3a3a3d;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    line-height: 48px;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    background-color: #9ca0a1;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".filebox input[type=\"file\"] {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    width: 0;\r\n");
      out.write("    height: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    border: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".filebox .upload-name {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    padding: 0 32px 0 12px;\r\n");
      out.write("    background: none;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("    border: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"text\"], input[type=\"password\"] {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 48px;\r\n");
      out.write("    padding: 0 16px;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    background-color: #fafafa;\r\n");
      out.write("    color: #1a1d1d;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    line-height: 48px;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 삭제버튼 */\r\n");
      out.write(".btn-reset {\r\n");
      out.write("    display: none;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 12px;\r\n");
      out.write("    right: 10px;\r\n");
      out.write("    width: 24px;\r\n");
      out.write("    height: 24px;\r\n");
      out.write("    background: url(../images/btn/btn_inp_reset.png) 0 0 no-repeat;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".regc {\r\n");
      out.write("	display : none;\r\n");
      out.write("	float : center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".evnt_inner_inpt{\r\n");
      out.write("    height: 48px;\r\n");
      out.write("    padding: 0 30px 0 16px;\r\n");
      out.write("    border: 1px solid #aeaeb2;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    background-color: #d7d7d7;\r\n");
      out.write("}\r\n");
      out.write("/* 첨부파일 영역 스타일적용 END */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("/**************************************************** \r\n");
      out.write("* 함수설명 : 수정/삭제버튼 클릭 이벤트\r\n");
      out.write("* * 수정일자 : 2024.04.02\r\n");
      out.write("* 수정내용 : 수정,삭제 버튼 클릭 시 노출메시지 구분 값 및 변수 추가\r\n");
      out.write("*         유효성검사(validation함수 파라미터 추가)\r\n");
      out.write("*         수정 / 삭제인 경우 호출 URL 분리\r\n");
      out.write("*****************************************************/\r\n");
      out.write("function updEvent(eventStatus){\r\n");
      out.write("	//debugger\r\n");
      out.write("	var inptTitle   = $('#title').val();\r\n");
      out.write("	var inptContent = $('#txtArea_content').val();\r\n");
      out.write("	var chkStatus   = $('input[name=\"eventYN\"]:checked').val();\r\n");
      out.write("	var inptEventStrtDt = $('#eventStrt').val();\r\n");
      out.write("	var inptEventEndDt  = $('#eventEnd').val();\r\n");
      out.write("	var writerNo = 1;\r\n");
      out.write("	var confirmMsg;	// 수정, 삭제 버튼 클릭 시 확인 메시지\r\n");
      out.write("	var eventfileImg = $('#fileName_110').val();\r\n");
      out.write("	console.log(\"inptEventStrtDt \" + inptEventStrtDt);\r\n");
      out.write("	console.log(\"inptEventEndDt \"  + inptEventEndDt);\r\n");
      out.write("	\r\n");
      out.write("	if(typeof eventStatus != \"undefined\"){\r\n");
      out.write("		if(eventStatus == \"UPD\") confirmMsg = \"게시글을 수정하시겠습니까?\";\r\n");
      out.write("		if(eventStatus == \"DEL\") confirmMsg = \"게시글을 삭제하시겠습니까?\";\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	//유효성 검사 함수 호출\r\n");
      out.write("	if(validation(eventStatus)){\r\n");
      out.write("		// confirm 함수는 확인창 결과값으로 TRUE와 FALSE 값을 RETURN 하게 됨.\r\n");
      out.write("		if(confirm(confirmMsg)){\r\n");
      out.write("		\r\n");
      out.write("		// 수정, 삭제부분 공통적인 부분 변수처리\r\n");
      out.write("		var eventNo = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventOne.eventNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("		var mappingUrl;\r\n");
      out.write("		var dataObj;\r\n");
      out.write("		var rsltMsg;\r\n");
      out.write("\r\n");
      out.write("		// 수정, 삭제인 경우 각각 데이터 세팅\r\n");
      out.write("		if(eventStatus == \"UPD\"){\r\n");
      out.write("			mappingUrl  = \"event.updInfo\";\r\n");
      out.write("			dataObj 	= {eventTitle : inptTitle, eventContent : inptContent, eventYN : chkStatus, \r\n");
      out.write("						   eventStrtDt : inptEventStrtDt, eventEndDt : inptEventEndDt,	      \r\n");
      out.write("						   eventImg : eventfileImg, eventNo : eventNo, writerNo : writerNo}\r\n");
      out.write("			rsltMsg     = \"게시글이 정상적으로 수정되었습니다.\";\r\n");
      out.write("		}\r\n");
      out.write("		if(eventStatus == \"DEL\"){\r\n");
      out.write("			mappingUrl  = \"event.delInfo\";\r\n");
      out.write("			dataObj 	= {eventNo : eventNo}\r\n");
      out.write("			rsltMsg     = \"게시글이 정상적으로 삭제되었습니다.\";\r\n");
      out.write("		}		\r\n");
      out.write("		\r\n");
      out.write("		// 게시글 저장 submission 정보 세팅		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type:\"POST\",\r\n");
      out.write("			url : mappingUrl,\r\n");
      out.write("			data : dataObj,\r\n");
      out.write("			\r\n");
      out.write("			// 정상적으로 처리되면 이벤트 목록으로 이동\r\n");
      out.write("			success:function(res){\r\n");
      out.write("			\r\n");
      out.write("			/*	if(res == \"SUCCESS\"){*/\r\n");
      out.write("					alert(rsltMsg);\r\n");
      out.write("					location.href=\"event.list\"\r\n");
      out.write("				/*}else{                   ?currentPage=1\r\n");
      out.write("					alert(rsltMsg);\r\n");
      out.write("					return;\r\n");
      out.write("				}*/\r\n");
      out.write("				},\r\n");
      out.write("				error:function(e){\r\n");
      out.write("					alert(\"이벤트 수정/삭제  중 오류가 발생하였습니다.\");\r\n");
      out.write("					return;\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("}	\r\n");
      out.write("	\r\n");
      out.write("/********************************* \r\n");
      out.write("* 함수설명 : 이벤트 수정 시 유효성 검사(필수값)\r\n");
      out.write("**********************************/\r\n");
      out.write("function validation(eventStatus){\r\n");
      out.write("	\r\n");
      out.write("	// 삭제버튼 클릭 시 skip 처리 함\r\n");
      out.write("	if(typeof eventStatus != \"undefined\" && eventStatus == \"DEL\") return true;\r\n");
      out.write("	\r\n");
      out.write("	// 각 필드 필수값 체크\r\n");
      out.write("	var content = $(\"#txtArea_content\").val();\r\n");
      out.write("	\r\n");
      out.write("	var today = new Date();\r\n");
      out.write("	var year    = today.getFullYear().toString();\r\n");
      out.write("	var month   = (\"00\" + (today.getMonth() + 1) ).toString().slice(-2);\r\n");
      out.write("	var day     = (\"00\" + today.getDate()).toString().slice(-2);\r\n");
      out.write("	var fullDay = year + \"-\" + month + \"-\" + day;\r\n");
      out.write("	\r\n");
      out.write("	// 이벤트 제목 체크\r\n");
      out.write("	if($(\"#title\").val() == \"\"){ \r\n");
      out.write("		alert(\"제목을 입력하세요.\");\r\n");
      out.write("		$(\"#title\").focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	// 라디오버튼 (게시여부) 체크여부 확인\r\n");
      out.write("	if( !$('input[name=\"eventYN\"]').is(':checked') ){\r\n");
      out.write("		alert(\"이벤트 진행상태를 선택해주세요.\");\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	// 이벤트 내용 체크\r\n");
      out.write("	if($(\"#txtArea_content\").val() == \"\"){\r\n");
      out.write("		alert(\"이벤트 내용을 입력해주세요.\");\r\n");
      out.write("		$(\"#txtArea_content\").focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}	\r\n");
      out.write("	\r\n");
      out.write("	// 이벤트 제목 글자수 체크\r\n");
      out.write("	if($(\"#title\").val().length > 30){ \r\n");
      out.write("		alert(\"이벤트 제목은 최대 30자까지만 입력 가능합니다.\");\r\n");
      out.write("		$(\"#title\").focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	// 이벤트 내용 글자수 체크\r\n");
      out.write("	if(content.length > 400){\r\n");
      out.write("		$(\"#txtArea_content\").val($(\"#txtArea_content\").val().substring(0, 400));\r\n");
      out.write("		alert(\"이벤트내용은 400자까지만 입력 가능합니다.\");\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	// 이벤트 시작일 체크\r\n");
      out.write("	if($(\"#eventStrt\").val() == \"\"){\r\n");
      out.write("		alert(\"시작날짜를 선택해주세요.\");	\r\n");
      out.write("		$(\"#eventStrt\").focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	//이벤트 종료일 체크\r\n");
      out.write("	if($(\"#eventEnd\").val()== \"\"){\r\n");
      out.write("		alert(\"종료날짜를 선택해주세요.\");\r\n");
      out.write("		$(\"#eventEnd\").focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	// 이벤트 시작일 종료일 범위 체크\r\n");
      out.write("	if($(\"#eventStrt\").val() > $(\"#eventEnd\").val()){\r\n");
      out.write("		alert(\"시작일은 종료일 보다 이전이어야 합니다.\");\r\n");
      out.write("		$(\"#eventStrt\").focus();\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	// 이벤트 시작일과 종료일은 현재 날짜보다 작을 수 없다\r\n");
      out.write("/* 	if($(\"#eventStrt\").val() < fullDay){\r\n");
      out.write("		alert(\"시작일은 현재날짜 보다 이전일 수 없습니다.\");\r\n");
      out.write("		$(\"#eventStrt\").focus();\r\n");
      out.write("		return;\r\n");
      out.write("	} */\r\n");
      out.write("	\r\n");
      out.write("	return true;\r\n");
      out.write("}	\r\n");
      out.write("	\r\n");
      out.write("/*********************************** \r\n");
      out.write("* 함수설명 : 이벤트 내용 글자 count하는 부분\r\n");
      out.write("************************************/\r\n");
      out.write("function countText(){\r\n");
      out.write("\r\n");
      out.write("	var content = $(\"#txtArea_content\").val();\r\n");
      out.write("	// 글자수 세기\r\n");
      out.write("	if(content.length == 0 || content == ''){\r\n");
      out.write("		$('#spn_textcount').text('0/400');\r\n");
      out.write("	}else{\r\n");
      out.write("		$('#spn_textcount').text(content.length + '/400');\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	// 글자 수 제한\r\n");
      out.write("	if(content.length > 400){\r\n");
      out.write("		$(\"#txtArea_content\").val($(\"#txtArea_content\").val().substring(0, 400));\r\n");
      out.write("		alert(\"이벤트등록은 400자까지만 입력 가능합니다.\");\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("}	\r\n");
      out.write("	\r\n");
      out.write("function upload(){\r\n");
      out.write("	//debugger\r\n");
      out.write("	console.log( $(\"#file_110\") );\r\n");
      out.write("	console.log($(\"#file_110\")[0].files[0].name);\r\n");
      out.write("	\r\n");
      out.write("	// 파일명 받기\r\n");
      out.write("	var fileName = \"\";\r\n");
      out.write("	if( typeof $(\"#file_110\")[0] != \"undefined\"){\r\n");
      out.write("		fileName = $(\"#file_110\")[0].files[0].name;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	// 파일명 upload 영역의 fileName_110인 요소에 세팅하기\r\n");
      out.write("	$(\"#fileName_110\").val(fileName);\r\n");
      out.write("	alert(\"첨부파일이 선택되었습니다.\");\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("	\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<!-- logo START -->\r\n");
      out.write("		<div id=\"logo\" class=\"logo_main\" align=\"center\"></div>\r\n");
      out.write("	<!-- logo END -->	\r\n");
      out.write("	\r\n");
      out.write("<!-- FORM 영역 START -->\r\n");
      out.write("	<form id=\"frm\" action=\"regEvent\" method=\"post\">\r\n");
      out.write("		<table class=\"table-light table-striped text-center\" width=\"100%\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th class=\"th_left\"><span>이벤트제목</span></th>\r\n");
      out.write("				<td><input type=\"text\" id=\"title\" name=\"eventTitle\" maxlength=\"26\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventOne.eventTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"width:650px;\"/></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			\r\n");
      out.write("       <tr>\r\n");
      out.write("       		<!-- 게시여부 영역  STRT -->  <!-- notice.getStatus()  -->\r\n");
      out.write("           	<th class=\"th_left\"><span>이벤트진행여부</span></th>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"radio-btn-wrap\" id=\"event_rdo_wrap\">\r\n");
      out.write("						<span class=\"radio-btn\">\r\n");
      out.write("								<!-- 조회 데이터 유무에 따른 처리  -->\r\n");
      out.write("							    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("								<label for=\"rdo_eventYNY\">진행</label>\r\n");
      out.write("						</span>\r\n");
      out.write("								\r\n");
      out.write("						<span class=\"radio-btn\">\r\n");
      out.write("								<!-- 조회 데이터 유무에 따른 처리  -->\r\n");
      out.write("							    ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("								\r\n");
      out.write("								<label for=\"rdo_eventYNN\">종료</label>\r\n");
      out.write("						</span>\r\n");
      out.write("					</div>\r\n");
      out.write("	            </td>\r\n");
      out.write("            <!-- 게시여부 영역  END -->\r\n");
      out.write("            \r\n");
      out.write("        </tr>			\r\n");
      out.write("			\r\n");
      out.write("       <tr>\r\n");
      out.write("            <th><span>이벤트내용</span>	</th>\r\n");
      out.write("            <td>\r\n");
      out.write("            	");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                \r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        \r\n");
      out.write("        <tr>  \r\n");
      out.write("        	<td></td>   \r\n");
      out.write("            <td>\r\n");
      out.write("            	<span id=\"spn_textcount\">0/400</span>\r\n");
      out.write("            		<script type=text/javascript>\r\n");
      out.write("            			// 공지사항 내용 세팅 후 글자수 세는 함수 호출\r\n");
      out.write("            			countText();\r\n");
      out.write("            		</script>\r\n");
      out.write("            </td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("         \r\n");
      out.write("         <!-- 이벤트 시작일, 종료일 전체영역 START -->\r\n");
      out.write("		<tr id=\"wrap_event\">\r\n");
      out.write("			<th><span>이벤트 기간</span><br><span>(시작일 / 종료일)</span></th>\r\n");
      out.write("				<td>\r\n");
      out.write("					<div class=\"toggle-group\"></div>\r\n");
      out.write("					<div class=\"radio-btn-wrap\" id=\"mixList_205\" style=\"display:none;\">\r\n");
      out.write("						<span class=\"radio-btn\">\r\n");
      out.write("							<label for=\"\">이벤트 기간(이벤트 시작일/종료일)</label>\r\n");
      out.write("						</span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"array-list\" data-attr_item_vlue=\"null\">\r\n");
      out.write("						<!-- 이벤트 시작일 -->\r\n");
      out.write("						<div class=\"item\">\r\n");
      out.write("							<div class=\"select-box bg-gray\" style=\"float:left; margin-right:10px;\">\r\n");
      out.write("								<!-- 이벤트 시작일 세팅 -->\r\n");
      out.write("								");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						<!-- 이벤트 종료일 -->\r\n");
      out.write("						<div class=\"item\">\r\n");
      out.write("							<div class=\"select-box bg-gray\" style=\"float:left; margin-right:10px;\">\r\n");
      out.write("								<!-- 이벤트 종료일 세팅 -->\r\n");
      out.write("								");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("					</div>\r\n");
      out.write("				</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<!-- 이벤트 시작일, 종료일 전체영역 END -->  \r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         <!-- 첨부파일 전체영역 START -->         \r\n");
      out.write("		<tr data-attr_seq=\"194\" data-attr_disp_form_cd=\"FD\" data-attr_calc_typ_cd=\"null\" data-attr_mndt_inpt_yn=\"Y\">	\r\n");
      out.write("			<th><span>첨부파일</span></th>	\r\n");
      out.write("			\r\n");
      out.write("			<td>\r\n");
      out.write("				<div class=\"filebox\">	\r\n");
      out.write("					<label for=\"file_110\" tabindex=\"0\">파일선택</label>	\r\n");
      out.write("						<input type=\"file\" id=\"file_110\" name=\"fileUpload\" data-file_id=\"110\" tabindex=\"-1\" onchange=\"upload();\">	\r\n");
      out.write("						<input type=\"hidden\" id=\"apndFileId_110\" data-attr_item_sno=\"\" data-prod_id=\"\">	\r\n");
      out.write("					\r\n");
      out.write("					<!-- 업로드 영역 START -->\r\n");
      out.write("					<div class=\"upload-box\">    \r\n");
      out.write("						<input type=\"text\" id=\"fileName_110\" name=\"eventImg\" class=\"upload-name inp\" placeholder=\"선택된 파일 없음\" title=\"선택된 파일 없음\" readonly=\"\">\r\n");
      out.write("						<button type=\"button\" id=\"fileReset\" class=\"btn-reset\"><span class=\"blind\">삭제</span></button>	\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- 업로드 영역 END -->\r\n");
      out.write("				</div>\r\n");
      out.write("					\r\n");
      out.write("					<ul class=\"list-text interval bullet\">	\r\n");
      out.write("						<!-- <li>허용 파일 형식 : pdf, jpg/jpeg, png, gif, doc/docx, hwp (15MB 미만)</li> -->\r\n");
      out.write("					</ul>	\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr> \r\n");
      out.write("		<!-- 첨부파일 전체영역 END -->         \r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td colspan=\"2\">\r\n");
      out.write("                <input type=\"button\" id=\"save\"   class=\"btn btn-primary\" value=\"수정\" onclick=\"updEvent('UPD');\"/>\r\n");
      out.write("                <input type=\"button\" id=\"save\"   class=\"btn btn-primary\" style=\"background-color:#eb008b; border-color:#eb008b;\" value=\"삭제\" onclick=\"updEvent('DEL')\" />\r\n");
      out.write("                <input type=\"button\" id=\"cancle\" class=\"btn btn-light\"   value=\"취소\" onclick=\"history.back();\"/>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("	</form>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- form태그 끝 -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/event/eventUpd.jsp(394,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty eventOne.eventYN}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									");
          if (_jspx_meth_c_005fchoose_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("									");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("									");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/event/eventUpd.jsp(396,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'Y' eq eventOne.eventYN}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("										<input type=\"radio\" id=\"rdo_eventYNY\" name=\"eventYN\" checked=\"\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventOne.eventYN}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("									");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("										<input type=\"radio\" id=\"rdo_eventYNY\" name=\"eventYN\" value=\"Y\">\r\n");
          out.write("									");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/event/eventUpd.jsp(409,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty eventOne.eventYN}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									");
          if (_jspx_meth_c_005fchoose_005f1(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("									");
          if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("									");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /WEB-INF/views/event/eventUpd.jsp(411,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'N' eq eventOne.eventYN}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("										<input type=\"radio\" id=\"rdo_eventYNN\" name=\"eventYN\" checked=\"\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventOne.eventYN}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("									");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f1_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("										<input type=\"radio\" id=\"rdo_eventYNN\" name=\"eventYN\" value=\"N\">\r\n");
          out.write("									");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      _jspx_th_c_005fotherwise_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/event/eventUpd.jsp(431,13) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty eventOne.eventContent}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            		<textarea rows=\"10\" cols=\"30\" id=\"txtArea_content\" name=\"eventContent\" onkeyup=\"countText();\"> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventOne.eventContent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" </textarea>\r\n");
          out.write("            	");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/views/event/eventUpd.jsp(465,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty eventOne.eventStrtDt}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									<input type=\"date\" id=\"eventStrt\" class=\"evnt_inner_inpt\" name=\"eventStrtDt\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventOne.eventStrtDt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /WEB-INF/views/event/eventUpd.jsp(475,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty eventOne.eventEndDt}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<input type=\"date\" id=\"eventEnd\" class=\"evnt_inner_inpt\" name=\"eventEndDt\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventOne.eventEndDt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }
}
