/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.99
 * Generated at: 2024-05-12 13:42:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.event;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class eventDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("	<title>더놀자 > 이벤트 > 상세</title>\r\n");
      out.write("	<style>\r\n");
      out.write("	      div{\r\n");
      out.write("            box-sizing : border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #wrap{\r\n");
      out.write("            width: 1200px;\r\n");
      out.write("            height: 1200px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #wrap > div{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #header, #footer {\r\n");
      out.write("            height: 15%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #content{\r\n");
      out.write("            height: 70%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #content_1{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height : 100%;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #footer{\r\n");
      out.write("			height: 15%;\r\n");
      out.write("			margin: auto;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	       \r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	#content_1{\r\n");
      out.write("	    width: 1200px;\r\n");
      out.write("	    margin : auto;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("#detail-area{\r\n");
      out.write("	width:100%;\r\n");
      out.write("	height:100%;\r\n");
      out.write("	word-break:break-all; /* 줄바꿈 처리 */\r\n");
      out.write("	/*border : 1px solid lightgreen;\r\n");
      out.write("    background-color: lightblue;\r\n");
      out.write("    color: white;\r\n");
      out.write("    font-weight: bold; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#detail_content-area{\r\n");
      out.write("	width:100%;\r\n");
      out.write("	height:100%;\r\n");
      out.write("    padding: 60px;\r\n");
      out.write("    border-bottom: 1px solid #d1d1d7;\r\n");
      out.write("    color: #1a1d1d;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    line-height: 26px;\r\n");
      out.write("    white-space: break-spaces;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".detail_content-area{\r\n");
      out.write("	display:block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".btn-wrap{\r\n");
      out.write("	display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    margin-top: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#detail-golist{\r\n");
      out.write("	width:448px;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("    background-color: #5BA199;\r\n");
      out.write("    border-color: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("	#contentHeader{\r\n");
      out.write("	 padding-top:5%;\r\n");
      out.write("	}\r\n");
      out.write("   \r\n");
      out.write("   .detail_date{\r\n");
      out.write("   	float : right;\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("img {\r\n");
      out.write("	padding-top:10%;\r\n");
      out.write("	padding-bottom:10%;\r\n");
      out.write("    margin: auto;\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	</style>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"outer\">\r\n");
      out.write("\r\n");
      out.write("	<br>\r\n");
      out.write("	<div class=\"align_center\">\r\n");
      out.write("		<h2 class=\"board-basic\">이벤트</h2>\r\n");
      out.write("	</div>\r\n");
      out.write("	<br>\r\n");
      out.write("	\r\n");
      out.write("	<br>\r\n");
      out.write("	<table id=\"detail-area\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"outer\">\r\n");
      out.write("<div id=\"content_1\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<table id=\"detail-area\">\r\n");
      out.write("        <div id=\"contentHeader\"><h2 align=\"left\">이벤트</h2></div>\r\n");
      out.write("\r\n");
      out.write("        <hr>\r\n");
      out.write("		<!-- 타이틀 영역 -->\r\n");
      out.write("	    <tr id=\"detail_title-area\">\r\n");
      out.write("	         <td class=\"detail_title_name_td\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${evnet.EventContent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("	         <td class=\"detail_date\">이벤트 기간 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ event.EventStrtDt }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('~');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ event.EventEndDt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>	\r\n");
      out.write("	    </tr>\r\n");
      out.write("	    <!-- 컨텐츠영역 -->		\r\n");
      out.write("	</table>\r\n");
      out.write("	<hr>\r\n");
      out.write("	<img src=\"resources/images/logo.png\">\r\n");
      out.write("		    \r\n");
      out.write("	<div class=\"btn-wrap\">\r\n");
      out.write("		<input type=\"button\" id=\"detail-golist\" class=\"btn btn-light\"   value=\"목록으로 이동\" onclick=\"history.back();\"/>\r\n");
      out.write("		\r\n");
      out.write("        <!--작성자 보이게끔-->\r\n");
      out.write("        <!--로그인 유저가 작성자와 같은지-->\r\n");
      out.write("        <!-- 로그인 여부 판단 그리고 로그인유저의 이름(UNIQUE)이랑 공지사항의 작성자 (사용하기엔 무리) 이것은 적합하지 않음 -->\r\n");
      out.write("        <!-- 새롭게 조회해온 USER_NO컬럼값을 가지고 비교    매핑값? SERVLET키값= -->\r\n");
      out.write("	</div>	\r\n");
      out.write("	<br>\r\n");
      out.write("	<br><br>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
